### ISSUE TITLE
本地运行程序后生成的文字无法在您提供的在线网页中解密，并且加密效果与网页版不同

### ISSUE THREAD

**Issue by tjyyy3** [guofei9987/text_blind_watermark#5]
pycharm中运行的结果，加密和解密效果正常：![image](https://github.com/guofei9987/text_blind_watermark/assets/97741063/de45949f-0ac7-4932-8fde-07fac3a5e5dc)
将加了密文的文字复制到word中：
![image](https://github.com/guofei9987/text_blind_watermark/assets/97741063/717cdb5e-36a9-43e8-9ac7-32bf9b4c978d)
将加了密文的文字复制到微信聊天框中：
![image](https://github.com/guofei9987/text_blind_watermark/assets/97741063/372687d5-1995-4fe8-9f6d-8705b6e192dc)
在在线网页中加密：
![image](https://github.com/guofei9987/text_blind_watermark/assets/97741063/9f95e34e-9326-4c6b-9887-e4da92df49d2)

想知道为什么在线加密的时候可以看出密文是间隔加在这段文字中的，但是在本地加密的时候密文只是加在文字中间部分

**Comment by Make-Ye** [comment]
没错，我也发现了这一情况（本地运行程序后生成的文字无法在作者提供的在线网页中解密），后经过分析，发现只需要把网站的text_embed += String.fromCharCode(0x200C);改成text_embed += String.fromCharCode(127);，似乎就能解决大部分这种情况。

**Comment by guofei9987** [comment]
> 没错，我也发现了这一情况（本地运行程序后生成的文字无法在作者提供的在线网页中解密），后经过分析，发现只需要把网站的text_embed += String.fromCharCode(0x200C);改成text_embed += String.fromCharCode(127);，似乎就能解决大部分这种情况。

最近发现使用 127（0x7F），在苹果系统上都能正常显示，但是在Windows和安卓系统上会显示出很多空格。经过测试，0x200C可以在尽量多的平台上正常显示，因此把网页版的 127 改为了 0x200C，python 版本还没来得及改。今天会更改和发布

**Comment by Make-Ye** [comment]
这样的情况建议把加密都改成0x200C，解密的部分可以判断使用的是0x7F还是0x200C，这样的话可以保证有些人用老版本的python程序也一样能在该在线网页中解密。

**Comment by guofei9987** [comment]
@Make-Ye @tjyyy3 
现在以下3个版本的运行结果已经可以互相通用：
1. python版本：https://github.com/guofei9987/text_blind_watermark
2. rust版本：https://github.com/guofei9987/hidden_watermark
3. 网页版：https://www.guofei.site/a/app/hidden_watermark/text_hidden_watermark.html

感谢使用，并提出建议🙏
