### ISSUE TITLE
请问，如果要实现word这类文档的盲水印有什么好的思路，感谢

### ISSUE THREAD

**Issue by ytfrdfiw** [guofei9987/text_blind_watermark#8]
如题，回复为盼！感谢。

**Comment by guofei9987** [comment]
> 如题，回复为盼！感谢。

已完成 docx/pptx/xlsx/pages/numbers/slides 类型的盲水印，不过短期内不会开源。  
思路是研究其文件结构，把水印插入文件结构中

**Comment by ytfrdfiw** [comment]
你好。再请教一下，就算是在文件结构中加入水印，如果泄密者将内容通过拷贝的方式将内容带走，这种也是没有办法的吧？包括如果对文件进行修改后，再保存，这种水印信息应该会丢失吧？感谢你的回复。
